from . import (
    domxss,
    sql_injection,
    xss_reflected,
    broken_auth,
    sensitive_data,
    xxe,
    broken_access,
    misconfig,
    insecure_deserialization,
    known_vulns,
    graphql,
    jwt,
    idor,
    ssrf,
    open_redirect,
    path_traversal,
    csrf,
    file_upload,
    security_headers,
    api_rate_limit,
    api_mass_assignment,
    ssti,
    # New modules
    lfi,
    rce,
    cors_misconfiguration,
    crlf_injection,
    prototype_pollution,
    subdomain_takeover,
    http_request_smuggling,
)

ALL_MODULES = [
    domxss,
    sql_injection,
    xss_reflected,
    broken_auth,
    sensitive_data,
    xxe,
    broken_access,
    misconfig,
    insecure_deserialization,
    known_vulns,
    graphql,
    jwt,
    idor,
    ssrf,
    open_redirect,
    path_traversal,
    csrf,
    file_upload,
    security_headers,
    api_rate_limit,
    api_mass_assignment,
    ssti,
    lfi,
    rce,
    cors_misconfiguration,
    crlf_injection,
    prototype_pollution,
    subdomain_takeover,
    http_request_smuggling,
]

MODULE_BY_NAME = {m.__name__.split(".")[-1]: m for m in ALL_MODULES}
